version: '3.11'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: test_app_blog_db
      POSTGRES_USER: test_app_blog_db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/test_app_blog
    ports:
      - "8000:8000"
    depends_on:
      - db

  bot:
    build: .
    command: python test_app_telegram_bot/bot.py
    volumes:
      - .:/test_app_blog
    depends_on:
      - db